### ISSUE TITLE
Can't run NoiseModelling - ERROR: Bundle [52] 

### ISSUE THREAD

**Issue by pierromond** [pierromond/NoiseModelling#12]
> ERROR: Bundle org.orbisgis.noisemap-core [52] Error starting file:/ [...] noisemap-core-2.2.0-SNAPSHOT.jar
> (org.osgi.framework.BundleException: Unresolved constraint in bundle org.orbisgi
> s.noisemap-core [52]: Unable to resolve 52.0: missing requirement [52.0] osgi.wi
> ring.package; (&(osgi.wiring.package=com.fasterxml.jackson.databind)(version>=2.
> 9.0)(!(version>=3.0.0))))
> org.osgi.framework.BundleException: Unresolved constraint in bundle org.orbisgis
> .noisemap-core [52]: Unable to resolve 52.0: missing requirement [52.0] osgi.wir
> ing.package; (&(osgi.wiring.package=com.fasterxml.jackson.databind)(version>=2.9
> .0)(!(version>=3.0.0)))

It seems that OrbisGIS can't import Noise Modelling...

**Comment by ebocher** [comment]
Could you please report this on OrbisGIS issue.
Thanks in advance.

**Comment by pierromond** [comment]
I think this issue is only true with my branch version..... Should I still report it?
